### ISSUE TITLE
Requires Android API level 28 (Android 9.0) due to the use of the BiometricPrompt

### ISSUE THREAD

**Issue by mduffy215** [duo-labs/android-webauthn-authenticator#1]
Would it be possible  to gain some functionality without the BiometricPrompt?

If so, what version of Android would be required?

Thx!

**Comment by nickmooney** [comment]
I believe you could use AndroidX's [BiometricPrompt compat implementation](https://developer.android.com/reference/androidx/biometric/BiometricPrompt) to bring down the required version. I'm not totally sure what the minimum version would be, but it would be significantly lower.

We would like to implement this but have no particular plan / timeline at the moment. We are open to pull requests.

Thanks for opening the issue!
