### ISSUE TITLE
Clarification of Usage ~ Roaming Authenticator via Bluetooth

### ISSUE THREAD

**Issue by mduffy215** [duo-labs/android-webauthn-authenticator#2]
Just to be clear, this code base is for creating an authenticator on a mobile device to be used by that mobile device.  This code base does not create an application that is "available as a roaming authenticator", correct"?

In section 6.2.1 the spec states, "For example, a platform authenticator integrated into a mobile device could make itself available as a roaming authenticator via Bluetooth. In this case the client would recognize it only as a roaming authenticator, and not as a platform authenticator."

Are there any samples available anywhere for creating a roaming authenticator on a mobile device and making it available by Bluetooth?  Thx!

**Comment by nickmooney** [comment]
You can use this library to create a roaming authenticator, but this does not implement that functionality for you. This library will handle the authenticator operations as listed in the WebAuthn spec, but you would have to implement the Bluetooth transport to use it in that fashion.

The only similar implementation I'm currently aware of is Google's CaBLE.

**Comment by mduffy215** [comment]
Thx Nick.  "CaBLE" is a very generic search term.  Do you by chance have a link?

**Comment by nickmooney** [comment]
Sure thing -- it stands for "cloud assisted Bluetooth Low Energy", and is the technical part behind Google's new ability to [use your Android phone as a security key](https://support.google.com/accounts/answer/9289445?hl=en). As far as I understand, it's Google-services-only for now.
